<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function record_cleaner_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  switch ($route_name) {
    case 'help.page.record_cleaner':
      $output .= '<h3>' . t("About") . '</h3>';

      $output .= '<p>';
      $output .= t("The Record Cleaner module allows users to upload CSV files
containing biological records for validation and verification. By validation
we mean ensuring that the data is in the correct format e.g that dates are
recognisable. By verification we mean checking that the observation falls within
the confines of a set of rules e.g. about where and when a species is found.

The verification rules have been written and are maintained by experts in their
field and are limited in scope to the British Isles.");
      $output .= '</p>';

      $output .= '<h3>' . t("Configuration") . '</h3>';
      $output .= '<p>';
      $output .= t("There are three settings to make in the <a href=':config'>
      Configuration</a> page. These are the service URL, username, and
      password.", [
        ':config' => Url::fromRoute('record_cleaner.config')->toString()
      ]);
      $output .= '</p>';
      $output .= '<ul><li>';
      $output .= t("The service URL is a link to an instance of the
      <a href=':service'>record cleaner service</a>.", [
        ':service' => Url::fromUri('https://github.com/BiologicalRecordsCentre/record-cleaner-service')->toString()
      ]);
      $output .= '</li><li>';
      $output .= t("The username and password are used to authenticate with
      the service. An administrator of the service will have to create an
      account for you and provide these details.");
      $output .= '</li></ul>';


      $output .= '<h3>' . t("Routes") . '</h3>';
      $output .= '<p>';
      $output .= t("The module adds three routes to your Drupal site. You will
      probably want to add menu items for each of these routes.");
      $output .= '</p>';
      $output .= '<ul><li>';
      $output .= t("The <a href=':intro'>introduction</a> page provides
a brief overview of how to use Record Cleaner.", [
        ':intro' => Url::fromRoute('record_cleaner')->toString()
      ]);
      $output .= '</li><li>';
      $output .= t("The service <a href=':status'>status</a> page provides
details of the current status of the service.", [
        ':status' => Url::fromRoute('record_cleaner.status')->toString()
      ]);
      $output .= '</li><li>';
      $output .= t("The <a href=':ui'>cleaner wizard</a> is where you upload
your CSV file and provide information about its contents so that validation
and verification can be performed.", [
        ':ui' => Url::fromRoute('record_cleaner.ui')->toString()
      ]);
      $output .= '</li></ul>';
    }

  return $output;
}
